"""
Описывает основного клиента сервиса.
"""
type Client {
  "Уникальный идентификатор клиента"
  id: ID!

  "Имя клиента"
  name: String

  "Возраст клиента"
  age: Int

  "Список документов, связанных с клиентом"
  documents: [Document]

  "Список родственников, связанных с клиентом"
  relatives: [Relative]
}

"""
Описывает документ, принадлежащий клиенту.
"""
type Document {
  "Уникальный идентификатор документа"
  id: ID!

  "Тип документа (например, Паспорт, Водительское удостоверение)"
  type: String

  "Номер документа"
  number: String

  "Дата выдачи документа"
  issueDate: String

  "Дата окончания срока действия документа"
  expiryDate: String
}

"""
Описывает родственника, связанного с клиентом.
"""
type Relative {
  "Уникальный идентификатор родственника"
  id: ID!

  "Тип родства (например, Супруг, Ребенок)"
  relationType: String

  "Имя родственника"
  name: String

  "Возраст родственника"
  age: Int
}

"""
Определяет корневые запросы (queries), доступные в API.
Это точки входа для получения данных.
"""
type Query {
  """
  Получение информации о клиенте по его ID.
  Позволяет гибко запрашивать связанные сущности (документы, родственников) в одном запросе.
  """
  client(id: ID!): Client
}

